# Generated by Django 4.2.16 on 2024-11-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contact_gardening_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='garden_zone',
            field=models.CharField(blank=True, choices=[('8a', '8a'), ('8b', '8b'), ('9a', '9a'), ('9b', '9b'), ('10a', '10a')], max_length=3, null=True, verbose_name='Which garden zone do you live in?'),
        ),
    ]
