# Generated by Django 4.2.16 on 2024-11-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_contact_garden_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gardening_experience',
            field=models.CharField(choices=[('novice', "I'm new to gardening"), ('intermediate', 'I have some experience'), ('advanced', "I'm an experienced gardener"), ('expert', "I'm a professional or expert gardener")], default='novice', max_length=20, verbose_name="What's your level of gardening experience? ()"),
        ),
    ]
