# Generated by Django 4.2.16 on 2024-11-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_member_story',
            field=models.BooleanField(default=False),
        ),
    ]
