# Generated by Django 4.2.16 on 2024-11-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_is_member_story_post_is_member_feature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_member_feature',
            new_name='is_member_story',
        ),
    ]
